<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-OB4CSQL" failures="1" tests="13" name="ejemplos.parallel.Asertos_Test" time="0.029" errors="0" timestamp="2021-06-08T11:25:27 CEST" skipped="1">
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test8" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test5" time="0.002"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test10" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test1" time="0.010"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test11" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test7" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test4" time="0.002"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test13" time="0.001">
    <skipped/>
  </testcase> <!-- test13 -->
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test3" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test12" time="0.005">
    <failure message="The following asserts failed:
	No es mayor que 10 expected [true] but found [false],
	No es menor que 0 expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
No es mayor que 10 expected [true] but found [false],
No es menor que 0 expected [true] but found [false]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at ejemplos.parallel.Asertos_Test.test12(Asertos_Test.java:188)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
]]>
    </failure>
  </testcase> <!-- test12 -->
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test6" time="0.001"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test9" time="0.002"/>
  <system-out/>
  <testcase classname="ejemplos.parallel.Asertos_Test" name="test2" time="0.001"/>
  <system-out/>
</testsuite> <!-- ejemplos.parallel.Asertos_Test -->
